examples: Fix windows build for adrv9002
The previous definitions for 'error' and 'info' were causing error
builds on windows:

adrv9002-iiostream.c(143,2): error C2143: syntax error: missing ')' before 'string'
adrv9002-iiostream.c(143,2): warning C4477: 'printf' : format string '%s' requires
an argument of type 'char *', but variadic argument 1 has type '__int64'

More specifically, the following line:
info("adrv9002 bandwidth: %lld\n", val);
Is expanded by the MSVC preprocessor like this:
printf("%s, %d: INFO: " "adrv9002 bandwidth: %lld\n", val "%s", __func__, 143, "");

The above won't compile as there is no comma between val and "%s".

This indicates that MSVC has issues with the order of expansion when variadic
macros are nested or passed through multiple levels.

Instead, use the do-while(0) patterns.

Signed-off-by: Dan Nechita <dan.nechita@analog.com>