tests: remove warnings on Centos 7 in iio_writedev/iio_readdev
We were getting:
error: 'name' may be used uninitialized in this function [-Werror=maybe-uninitialized]
     printf("Example : " MY_NAME " -u %s -b 256 -s 1024 %s\n",

because, well - we were using it uninitialized...

Initialize it properly

Signed-off-by: Robin Getz <robin.getz@analog.com>